### PR TITLE
chore: expose starvation monitoring config

### PR DESCRIPTION
**Pull request by omerlh**
Exposing all metrics and make them configureable: https://typelevel.org/cats-effect/docs/core/starvation-and-tuning

### CODE REVIEW

**Review by guysegal — COMMENTED** [review]
I assume this is for debugging the problem?

**Comment by omerlh** [comment]
I think it's good values to give the end user control over in general, let them decide if and how they want to use this feature

**Comment by guysegal** [comment]
Not really, I want to simplify the user's life and not let him think about the value of `CPU_STARVATION_CHECK_INITIAL_DELAY_MS` - he will probably won't know how to define it properly.

**Comment by omerlh** [comment]
Yep so by default you will never set it, but if you do - it's there for you

**Comment by guysegal** [comment]
there's something I don't understand here - which operation is blocking the begin with? you are using sendAsync that should be async

**Comment by omerlh** [comment]
This is why I want to open up those configuration, it might also be bad JVM configuration. Be default most users will never use them. But, if you see this weird error you can debug it now

**Comment by guysegal** [comment]
ok, so lets use them for debugging, and if when we'll understand the I prefer to remove them, they are specific `cats-effect` configuration which is very much an implementation detail (if I'd like to change cats-effect to different asynchronous runtime I don't want to do breaking changes of env vars)

**Comment by omerlh** [comment]
Ok, Let's merge?

**Review by guysegal — APPROVED** [review]

**Pull request merged**
